<a href="https://colab.research.google.com/github/saikumarreddykorsapati-source/LEARN-/blob/main/NUMPY_Complete_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array is faster than list in python

In [6]:
import numpy as np  # importing numpy library as alias np

In [28]:
arr = np.array([1,2,3,'sai',2+4j]) # generating a one dimensional array

In [29]:
arr

array(['1', '2', '3', 'sai', '(2+4j)'], dtype='<U21')

In [61]:
arr.ndim # used to check dimenstionality of the array ie., whether 1D or 2D or 3D...

1

In [4]:
type(arr) # provides data type 

numpy.ndarray

In [30]:
np.array([2,3,4,6.2]) 
# if we specify one element as high data type and remaning as low data type automatically remaning elements will be type casted or 
# upcasted into higher data type, ie., here all the int type are type casted into float

array([2. , 3. , 4. , 6.2])

In [63]:
np.array([[3,4],[2,3],[6,5]]) # generate 2D array

array([[3, 4],
       [2, 3],
       [6, 5]])

In [33]:
np.array([[3,4],[2,3],[6,5,7]]) # here we specified one list with more elements ie.,3 so this array stores all the elements as list

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([3, 4]), list([2, 3]), list([6, 5, 7])], dtype=object)

In [38]:
np.array([1,2,3,4,5,6,7,8,8,9], ndmin = 3) 
# by using ndmin we are specifiying the dimension (1D/2D/3D/...) array to be generated with specified values

array([[[1, 2, 3, 4, 5, 6, 7, 8, 8, 9]]])

In [64]:
np.array([1,2,3,4,5,6,7,8,8,9],ndmin = 3).ndim # used to identify dimenstionality of the array ie., whether 1D or 2D or 3D...

3

### **Note :** ndmin and ndim are separate
ndmin is used while generating array to specify number of dimensions whereas 
ndim is used to identify number of dimensions od already generated array

In [40]:
np.array([1,2,3], dtype = complex) # using dtype we can specify the datatype of elements in the array

array([1.+0.j, 2.+0.j, 3.+0.j])

In [41]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [65]:
arr = np.array([(1,2),(4,5)], dtype= [("a",'<i4'),("b",'<i8')]) # by deafult i4 is considered in jupiter notebook in google collab i8 
# i2 = 16bit, i4 = 32bit, i8 = 64bit, this convention is mostly used while creating libraries
# i2 = 2*8bits = 16bits ; i4 = 4*8bits = 32bits ; i8 = 8*8bits = 64bits

In [55]:
type(arr[0][0])

numpy.int32

In [56]:
type(arr[0][1])

numpy.int64

In [69]:
arr  = np.array([[1,3],[3,4]])

In [72]:
type(arr[0][1]) # by deafult i4 is considered in jupiter notebook in google collab i8

numpy.int64

# **What is a matrix in numpy?**
matrix. Returns a matrix from an array-like object, or from a string of data. ... A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).
### **Note :**
Matrix is subset of numpy array

np.mat(array) or np.matrix(array) is used to generate matrix

In [74]:
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [75]:
np.matrix(arr)

matrix([[1, 2],
        [3, 4]])

In [77]:
l =[1,2,3,4] # list 

np.array() , np.asarray() , np.asanyarray() all are used to convert no array data into array type
suppose if data is already in any of the array type then np.asanyarray() cannot convert it into array form whereas other two can do

In [78]:
np.array(l)

array([1, 2, 3, 4])

In [79]:
np.asarray(l)

array([1, 2, 3, 4])

In [80]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [81]:
np.asanyarray(mat) # though matrix is a form of array, np.asanyarray() cannot convert it into array

matrix([[1, 2],
        [3, 4]])

In [82]:
np.asarray(mat) # by using asarray we can convert any type of data into array type

array([[1, 2],
       [3, 4]])

In [83]:
np.array(mat)

array([[1, 2],
       [3, 4]])

In [89]:
issubclass(np.matrix,np.ndarray) # here we can check matrix is a subclass of numpy array or not

True

In [87]:
issubclass(np.ndarray,np.matrix) # here we can check numpy array is a subclass of matrix or not

False

## **Shallow Copy and Deep Copy**

numpy array is mutable so we can make cahnges to existing array

**ShallowCopy:**

if we assign an Original array to a variable it just refer to that array location, in such a case if we do any change in that Original array the change will reflect in that a variable as well.

**DeepCopy:**

using np.copy() if we assign an Original array to a variable it creates an another  copy of that array in other location and then assigned to that variable, so if we perform any change on that Original array it will not reflect in that varible.

In [90]:
arr = np.array([[1,2,3],[4,5,6]])

In [91]:
arr # Original Array

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a = arr   # Shallow Copy
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b = np.copy(arr) # Deep Copy
b

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr # Original Array

array([[1, 7, 3],
       [4, 5, 6]])

In [100]:
arr[0][1] = 7 # chaning value of original array

In [101]:
a # Shallow Copy result

array([[1, 7, 3],
       [4, 5, 6]])

In [103]:
b # Deep Copy result

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr[-1] # we can even use -1 to access elements from back side

array([4, 5, 6])

In [60]:
arr.ndim # identifying dimensionality of array

1

In [59]:
np.array([[1,2,3,4],[5,6,7,8]]) # generating 2 dimensional array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
for i in arr: # we can even perform iteration on numpy array
  print(i)

[1 7 3]
[4 5 6]


In [110]:
np.fromfunction(lambda i,j : i==j , (4,4)) 
# using np.fromfunction we can get values from functions as well and then we can convert them into numpy array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [111]:
type(np.fromfunction(lambda i,j : i==j , (4,4)))

numpy.ndarray

In [118]:
np.fromfunction(lambda i,j : i*j , (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [119]:
np.fromfunction(lambda i,j : i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [120]:
np.fromfunction(lambda i,j : i/j, (3,3))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [1]:
0/0

ZeroDivisionError: ignored

In [2]:
1/0

ZeroDivisionError: ignored

In [3]:
gen = (i*i for i in range(5))

In [4]:
gen

<generator object <genexpr> at 0x7fd50d265250>

In [7]:
def test(x):
  yield x
test(5)

<generator object test at 0x7fd50d1d7550>

In [8]:
for i in gen:
  print(i)

0
1
4
9
16


In [12]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [14]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

In [15]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [17]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [19]:
type(arr1)

numpy.ndarray

In [22]:
arr1.ndim

2

In [25]:
arr1.size # it provide of count of elements in the array

12

In [26]:
arr1.shape # provides NXM (N cross M), N = number of rows ; M = number of columns of an array

(3, 4)

In [27]:
arr1.dtype # provides data type of elements in array

dtype('int64')

In [40]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [42]:
arr.size

4

In [43]:
arr.shape

(4,)

In [44]:
arr.ndim

1

In [50]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[32,32,32,32],[9,10,11,12]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[32, 32, 32, 32],
        [ 9, 10, 11, 12]]])

In [51]:
arr2.ndim

3

In [52]:
arr2.size

16

In [53]:
arr2.shape  # here (2,2,4) defines last 4 refers to columns (M) , last but 2nd 2 refers to rows (N), 
#first number 2 referes number of layers with such N X M

(2, 2, 4)

In [54]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [57]:
arr4.ndim

4

In [58]:
arr4.shape

(1, 4, 2, 4)

In [59]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [60]:
list(range(5.0,10.0)) # floating point values wont work in this case

TypeError: ignored

In [62]:
np.arange(5.0,10.0) # to resolve above this np.arange() function will be used

array([5., 6., 7., 8., 9.])

In [63]:
np.arange(5.0,10.0,2) # we can also perform negative slicing as well

array([5., 7., 9.])

In [66]:
np.linspace(1,10) # by default 50 values will be provided

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
np.linspace(1,10,5) # we are requesting only 5 values with in that range
# here the upper bound may be 10.00000000000000000001 may be something so we are getting 10 in output

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [68]:
np.zeros(5) # provides us an array of complete 0 elements with specified range

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.zeros((2,5,4)) # 2 layers of 5 X 4 arrays in 3D array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
np.ones(5) # provides us an array of complete 1 elements with specified range

array([1., 1., 1., 1., 1.])

In [112]:
np.ones([5,2]) 

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [75]:
np.ones(((2,5,4)))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [76]:
np.ones(((2,5,4)))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [77]:
np.empty(5)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304])

In [79]:
np.empty((3,4))

array([[4.65960365e-310, 2.35541533e-312, 2.14321575e-312,
        8.48798317e-313],
       [8.48798317e-313, 9.33678148e-313, 9.33678148e-313,
        8.70018275e-313],
       [8.70018274e-313, 1.12465777e-312, 1.01855798e-312,
        1.46030983e-319]])

In [115]:
np.empty([5,9])

array([[4.64180559e-310, 1.58595072e-321, 0.00000000e+000,
        0.00000000e+000, 2.43565992e-154, 3.16251369e+180,
        3.74271162e+233, 4.31906163e-096, 1.14568603e+243],
       [5.48912304e-143, 1.29060660e+248, 1.16071791e-028,
        2.28176674e+243, 9.31115425e+242, 2.59031262e-144,
        2.86530729e+161, 2.11329502e+214, 7.49511203e+247],
       [1.12284826e+219, 1.94919754e-153, 3.50896888e+151,
        2.59903818e-144, 4.97750675e+151, 9.08367206e+223,
        1.48890323e+195, 1.39028129e-142, 7.69152992e+218],
       [1.23762599e+224, 1.04918335e-153, 5.82659549e+252,
        2.24154146e+174, 1.09936966e+248, 6.42618040e-095,
        7.92521264e+068, 7.29489530e+175, 1.04989162e-153],
       [5.39840330e+242, 2.16209963e+233, 4.06762684e-144,
        3.99256150e+252, 9.18178269e+170, 5.49811678e-143,
        1.09600041e+296, 6.12033286e+257, 7.03044823e-143]])

In [80]:
np.eye(5) # The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(5,5) # The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [98]:
np.linspace([1,2,3,4],5,endpoint=False,axis=1)

array([[1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
        1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
        2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
        3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
        4.52, 4.6 , 4.68, 4.76, 4.84, 4.92],
       [2.  , 2.06, 2.12, 2.18, 2.24, 2.3 , 2.36, 2.42, 2.48, 2.54, 2.6 ,
        2.66, 2.72, 2.78, 2.84, 2.9 , 2.96, 3.02, 3.08, 3.14, 3.2 , 3.26,
        3.32, 3.38, 3.44, 3.5 , 3.56, 3.62, 3.68, 3.74, 3.8 , 3.86, 3.92,
        3.98, 4.04, 4.1 , 4.16, 4.22, 4.28, 4.34, 4.4 , 4.46, 4.52, 4.58,
        4.64, 4.7 , 4.76, 4.82, 4.88, 4.94],
       [3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 ,
        3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72, 3.76, 3.8 , 3.84,
        3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16, 4.2 , 4.24, 4.28,
        4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 , 4.64, 4.68, 4.72,
        4.76, 4.8 , 4.

In [109]:
np.linspace(2,[5,6,7],axis=0)

array([[2.        , 2.        , 2.        ],
       [2.06122449, 2.08163265, 2.10204082],
       [2.12244898, 2.16326531, 2.20408163],
       [2.18367347, 2.24489796, 2.30612245],
       [2.24489796, 2.32653061, 2.40816327],
       [2.30612245, 2.40816327, 2.51020408],
       [2.36734694, 2.48979592, 2.6122449 ],
       [2.42857143, 2.57142857, 2.71428571],
       [2.48979592, 2.65306122, 2.81632653],
       [2.55102041, 2.73469388, 2.91836735],
       [2.6122449 , 2.81632653, 3.02040816],
       [2.67346939, 2.89795918, 3.12244898],
       [2.73469388, 2.97959184, 3.2244898 ],
       [2.79591837, 3.06122449, 3.32653061],
       [2.85714286, 3.14285714, 3.42857143],
       [2.91836735, 3.2244898 , 3.53061224],
       [2.97959184, 3.30612245, 3.63265306],
       [3.04081633, 3.3877551 , 3.73469388],
       [3.10204082, 3.46938776, 3.83673469],
       [3.16326531, 3.55102041, 3.93877551],
       [3.2244898 , 3.63265306, 4.04081633],
       [3.28571429, 3.71428571, 4.14285714],
       [3.

In [112]:
np.logspace(3,5,axis=0)

array([  1000.        ,   1098.54114199,   1206.79264064,   1325.71136559,
         1456.3484775 ,   1599.85871961,   1757.51062485,   1930.69772888,
         2120.95088792,   2329.95181052,   2559.5479227 ,   2811.76869797,
         3088.84359648,   3393.2217719 ,   3727.59372031,   4094.91506238,
         4498.43266897,   4941.71336132,   5428.67543932,   5963.62331659,
         6551.2855686 ,   7196.85673001,   7906.04321091,   8685.11373751,
         9540.9547635 ,  10481.13134155,  11513.95399326,  12648.55216855,
        13894.95494373,  15264.17967175,  16768.32936811,  18420.69969327,
        20235.89647725,  22229.96482526,  24420.53094549,  26826.9579528 ,
        29470.51702552,  32374.57542818,  35564.80306223,  39069.39937055,
        42919.34260129,  47148.66363457,  51794.74679231,  56898.66029018,
        62505.51925274,  68664.88450043,  75431.20063355,  82864.27728547,
        91029.81779915, 100000.        ])

In [116]:
d= np.linspace(4,5,9)
d

array([4.   , 4.125, 4.25 , 4.375, 4.5  , 4.625, 4.75 , 4.875, 5.   ])

In [117]:
d.ndim

1

In [119]:
d.shape

(9,)

In [141]:
d.reshape(9,1) # reshaped into 2d array

array([[4.   ],
       [4.125],
       [4.25 ],
       [4.375],
       [4.5  ],
       [4.625],
       [4.75 ],
       [4.875],
       [5.   ]])

In [148]:
d.reshape(1,3,3) # reshaped into 3 d array with 1 layer of 3 rows 3 cols

array([[[4.   , 4.125, 4.25 ],
        [4.375, 4.5  , 4.625],
        [4.75 , 4.875, 5.   ]]])

In [139]:
d.reshape(9) # reshaped into 1 d array

array([4.   , 4.125, 4.25 , 4.375, 4.5  , 4.625, 4.75 , 4.875, 5.   ])

In [147]:
np.logspace(1,2,5) # np.logspace(start, stop, number of values needed)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [5]:
np.random.rand(5)

array([0.10865051, 0.66228124, 0.54099558, 0.10903099, 0.48132367])

In [6]:
np.random.randn(5)

array([-0.38818864, -0.84794385, -1.68105662,  1.69652888, -0.2983415 ])

In [160]:
np.random.randn(1,4,3) # np.random.randn(layers,rows,cols)

array([[[-0.98103651, -0.22248211, -0.78670479],
        [ 0.70672999, -0.65628486, -0.67059936],
        [-1.81323802, -2.15595309,  0.64993986],
        [-0.80736341, -0.09683859,  0.30669931]]])

In [14]:
np.random.randint(5,10, (4,4))

array([[5, 6, 9, 7],
       [9, 8, 8, 5],
       [9, 7, 6, 7],
       [5, 6, 5, 7]])

In [163]:
np.random.randn(2,2,4)

array([[[-0.50226477, -1.17223343, -0.66719074,  0.50980143],
        [-1.28867874,  1.14117913,  0.25963431, -0.17558434]],

       [[-0.13950291, -0.29983754,  1.05258994,  1.46891686],
        [-1.66723583, -0.03960145, -0.54365929,  0.84536454]]])

In [165]:
arr = np.random.randint(3,9,(3,3))
arr

array([[3, 6, 7],
       [6, 4, 6],
       [3, 5, 5]])

In [174]:
arr.reshape(1,9)

array([[3, 6, 7, 6, 4, 6, 3, 5, 5]])

In [175]:
arr.reshape(9,1)

array([[3],
       [6],
       [7],
       [6],
       [4],
       [6],
       [3],
       [5],
       [5]])

In [176]:
arr.reshape(1,1,9)

array([[[3, 6, 7, 6, 4, 6, 3, 5, 5]]])

In [177]:
arr.reshape(3,3,1)

array([[[3],
        [6],
        [7]],

       [[6],
        [4],
        [6]],

       [[3],
        [5],
        [5]]])

In [178]:
arr.reshape(3,-1) 
# other than -1 we can also give any negative value, reshape is smart enough to define cols automatically if we put negative values

array([[3, 6, 7],
       [6, 4, 6],
       [3, 5, 5]])

In [179]:
arr.reshape(1,-1)

array([[3, 6, 7, 6, 4, 6, 3, 5, 5]])

In [180]:
arr

array([[3, 6, 7],
       [6, 4, 6],
       [3, 5, 5]])

In [181]:
arr.max()

7

In [182]:
arr.min()

3

In [183]:
arr.mean()

5.0

In [7]:
arr = np.random.randint(4,100,(5,5))
arr

array([[78, 91, 87, 78, 84],
       [22,  7, 53,  4, 94],
       [99, 49, 59, 91, 44],
       [86, 71, 97, 43, 73],
       [28, 87, 57, 27, 49]])

In [192]:
arr[3:,3:]

array([[71, 62],
       [13, 74]])

In [10]:
arr[:,[1,3]] # gives all rows and 1,3 columns

array([[91, 78],
       [ 7,  4],
       [49, 91],
       [71, 43],
       [87, 27]])

In [11]:
arr[arr>10] # gives all the elements which are greater than 10

array([78, 91, 87, 78, 84, 22, 53, 94, 99, 49, 59, 91, 44, 86, 71, 97, 43,
       73, 28, 87, 57, 27, 49])

In [12]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
arr * arr # here we are only multiplying elements of each row and each columns with another array of same, This is not matrix multiplication

array([[6084, 8281, 7569, 6084, 7056],
       [ 484,   49, 2809,   16, 8836],
       [9801, 2401, 3481, 8281, 1936],
       [7396, 5041, 9409, 1849, 5329],
       [ 784, 7569, 3249,  729, 2401]])

In [14]:
arr@arr # This is Matrix Multiplication

array([[25759, 24844, 29096, 19987, 28744],
       [10093, 13110, 11158,  9277,  9736],
       [23699, 22532, 26026, 18388, 24317],
       [23615, 22480, 25300, 19639, 24882],
       [13435, 12130, 15822, 10203, 17410]])

In [15]:
arr1 = np.random.randint(2,4,(3,3))
arr2 = np.random.randint(2,4,(3,3))

In [16]:
arr1

array([[2, 3, 3],
       [2, 2, 3],
       [2, 2, 3]])

In [17]:
arr2

array([[2, 3, 3],
       [2, 3, 3],
       [2, 3, 2]])

In [18]:
arr1 * arr2

array([[4, 9, 9],
       [4, 6, 9],
       [4, 6, 6]])

In [19]:
arr1@arr2

array([[16, 24, 21],
       [14, 21, 18],
       [14, 21, 18]])

In [20]:
arr/0 # inf means infinity value

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [21]:
arr**2

array([[6084, 8281, 7569, 6084, 7056],
       [ 484,   49, 2809,   16, 8836],
       [9801, 2401, 3481, 8281, 1936],
       [7396, 5041, 9409, 1849, 5329],
       [ 784, 7569, 3249,  729, 2401]])

In [22]:
arr1 + 2

array([[4, 5, 5],
       [4, 4, 5],
       [4, 4, 5]])

In [27]:
arr1.reshape(9,1) + arr2.reshape(9,1)

array([[4],
       [6],
       [6],
       [4],
       [5],
       [6],
       [4],
       [5],
       [5]])

In [29]:
arr1

array([[2, 3, 3],
       [2, 2, 3],
       [2, 2, 3]])

In [28]:
arr1.T # applying Transpose

array([[2, 2, 2],
       [3, 2, 2],
       [3, 3, 3]])

In [30]:
np.sqrt(arr1) #square root

array([[1.41421356, 1.73205081, 1.73205081],
       [1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 1.73205081]])

In [31]:
np.exp(arr1) #exponential

array([[ 7.3890561 , 20.08553692, 20.08553692],
       [ 7.3890561 ,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 , 20.08553692]])

In [33]:
np.log10(arr) #log with base 10

array([[1.8920946 , 1.95904139, 1.93951925, 1.8920946 , 1.92427929],
       [1.34242268, 0.84509804, 1.72427587, 0.60205999, 1.97312785],
       [1.99563519, 1.69019608, 1.77085201, 1.95904139, 1.64345268],
       [1.93449845, 1.85125835, 1.98677173, 1.63346846, 1.86332286],
       [1.44715803, 1.93951925, 1.75587486, 1.43136376, 1.69019608]])

In [36]:
np.log2(arr)

array([[6.28540222, 6.50779464, 6.4429435 , 6.28540222, 6.39231742],
       [4.45943162, 2.80735492, 5.72792045, 2.        , 6.55458885],
       [6.62935662, 5.61470984, 5.88264305, 6.50779464, 5.45943162],
       [6.42626475, 6.14974712, 6.59991284, 5.42626475, 6.18982456],
       [4.80735492, 6.4429435 , 5.83289001, 4.7548875 , 5.61470984]])

In [40]:
np.random.seed(13) # by using seed we can provide same random values everytime we execute
np.random.randn(2,3)

array([[-0.71239066,  0.75376638, -0.04450308],
       [ 0.45181234,  1.34510171,  0.53233789]])