<a href="https://colab.research.google.com/github/saikumarreddykorsapati-source/LEARN-/blob/main/NUMPY_Complete_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  # importing numpy library as alias np

In [28]:
arr = np.array([1,2,3,'sai',2+4j]) # generating a one dimensional array

In [29]:
arr

array(['1', '2', '3', 'sai', '(2+4j)'], dtype='<U21')

In [61]:
arr.ndim # used to check dimenstionality of the array ie., whether 1D or 2D or 3D...

1

In [4]:
type(arr) # provides data type 

numpy.ndarray

In [30]:
np.array([2,3,4,6.2]) 
# if we specify one element as high data type and remaning as low data type automatically remaning elements will be type casted or 
# upcasted into higher data type, ie., here all the int type are type casted into float

array([2. , 3. , 4. , 6.2])

In [63]:
np.array([[3,4],[2,3],[6,5]]) # generate 2D array

array([[3, 4],
       [2, 3],
       [6, 5]])

In [33]:
np.array([[3,4],[2,3],[6,5,7]]) # here we specified one list with more elements ie.,3 so this array stores all the elements as list

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([3, 4]), list([2, 3]), list([6, 5, 7])], dtype=object)

In [38]:
np.array([1,2,3,4,5,6,7,8,8,9], ndmin = 3) 
# by using ndmin we are specifiying the dimension (1D/2D/3D/...) array to be generated with specified values

array([[[1, 2, 3, 4, 5, 6, 7, 8, 8, 9]]])

In [64]:
np.array([1,2,3,4,5,6,7,8,8,9],ndmin = 3).ndim # used to identify dimenstionality of the array ie., whether 1D or 2D or 3D...

3

### **Note :** ndmin and ndim are separate
ndmin is used while generating array to specify number of dimensions whereas 
ndim is used to identify number of dimensions od already generated array

In [40]:
np.array([1,2,3], dtype = complex) # using dtype we can specify the datatype of elements in the array

array([1.+0.j, 2.+0.j, 3.+0.j])

In [41]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [65]:
arr = np.array([(1,2),(4,5)], dtype= [("a",'<i4'),("b",'<i8')]) # by deafult i4 is considered in jupiter notebook in google collab i8 
# i2 = 16bit, i4 = 32bit, i8 = 64bit, this convention is mostly used while creating libraries
# i2 = 2*8bits = 16bits ; i4 = 4*8bits = 32bits ; i8 = 8*8bits = 64bits

In [55]:
type(arr[0][0])

numpy.int32

In [56]:
type(arr[0][1])

numpy.int64

In [69]:
arr  = np.array([[1,3],[3,4]])

In [72]:
type(arr[0][1]) # by deafult i4 is considered in jupiter notebook in google collab i8

numpy.int64

# **What is a matrix in numpy?**
matrix. Returns a matrix from an array-like object, or from a string of data. ... A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).
### **Note :**
Matrix is subset of numpy array

np.mat(array) or np.matrix(array) is used to generate matrix

In [74]:
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [75]:
np.matrix(arr)

matrix([[1, 2],
        [3, 4]])

In [77]:
l =[1,2,3,4] # list 

np.array() , np.asarray() , np.asanyarray() all are used to convert no array data into array type
suppose if data is already in any of the array type then np.asanyarray() cannot convert it into array form whereas other two can do

In [78]:
np.array(l)

array([1, 2, 3, 4])

In [79]:
np.asarray(l)

array([1, 2, 3, 4])

In [80]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [81]:
np.asanyarray(mat) # though matrix is a form of array, np.asanyarray() cannot convert it into array

matrix([[1, 2],
        [3, 4]])

In [82]:
np.asarray(mat) # by using asarray we can convert any type of data into array type

array([[1, 2],
       [3, 4]])

In [83]:
np.array(mat)

array([[1, 2],
       [3, 4]])

In [89]:
issubclass(np.matrix,np.ndarray) # here we can check matrix is a subclass of numpy array or not

True

In [87]:
issubclass(np.ndarray,np.matrix) # here we can check numpy array is a subclass of matrix or not

False

## **Shallow Copy and Deep Copy**

numpy array is mutable so we can make cahnges to existing array

**ShallowCopy:**

if we assign an Original array to a variable it just refer to that array location, in such a case if we do any change in that Original array the change will reflect in that a variable as well.

**DeepCopy:**

using np.copy() if we assign an Original array to a variable it creates an another  copy of that array in other location and then assigned to that variable, so if we perform any change on that Original array it will not reflect in that varible.

In [90]:
arr = np.array([[1,2,3],[4,5,6]])

In [91]:
arr # Original Array

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a = arr   # Shallow Copy
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b = np.copy(arr) # Deep Copy
b

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr[0][1] = 7

In [102]:
arr # Original Array

array([[1, 7, 3],
       [4, 5, 6]])

In [101]:
a # Shallow Copy

array([[1, 7, 3],
       [4, 5, 6]])

In [103]:
b # Deep Copy

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.array([[1,2,3,4],[5,6,7,8]]) # generating 2 dimensional array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
arr.ndim

1

In [5]:
np.random.rand(5)

array([0.10865051, 0.66228124, 0.54099558, 0.10903099, 0.48132367])

In [6]:
np.random.randn(5)

array([-0.38818864, -0.84794385, -1.68105662,  1.69652888, -0.2983415 ])

In [14]:
np.random.randint(5,10, (4,4))

array([[5, 6, 9, 7],
       [9, 8, 8, 5],
       [9, 7, 6, 7],
       [5, 6, 5, 7]])

In [23]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])